services:
  health-receiver:
    image: dzarlax/health_dashboard:latest
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/data
    environment:
      - DB_PATH=/app/data/health.db
      # - API_KEY=your-secret-key
      # - UI_PASSWORD=your-ui-password
    restart: unless-stopped

